/* Reuses the existing app feature handlers and server client. */
(()=>{
 'use strict';document.body.classList.add('pyeoda-music');document.querySelector('meta[name="theme-color"]')?.setAttribute('content','#0d0d12');const css=document.querySelector('link[data-pyeoda-music]');if(css)document.head.append(css);
 const logo=document.querySelector('.top .logo');if(logo){logo.innerHTML='<span>PYODA BOOKS</span><small>BOOKS FOR CREATORS</small>';logo.setAttribute('aria-label','PYODA BOOKS 홈');}
 const install=document.getElementById('pyeodaInstallEntry');if(install){install.textContent='↓ 앱 설치';install.setAttribute('aria-label','PC·모바일에 펴다 앱 설치');}
 const hero=document.querySelector('#home .hero');if(hero){hero.querySelector('.eyebrow').textContent='YOUR NEXT STORY';hero.querySelector('h1').innerHTML='마음에 남을 이야기,<br>여기서 펼쳐보세요.';const copy=hero.querySelector('.hero-copy')||hero.querySelector('p');copy.textContent='무료 작품부터 소장까지, 마음에 남는 이야기를 만나보세요.';const policy=document.createElement('p');policy.className='books-home-policy';policy.textContent='무료 읽기 · 무료 글쓰기';hero.querySelector('.cta')?.after(policy);const d=hero.querySelector('.mobile-home-details');if(d){d.querySelector('summary').textContent='펴다 이용·수익 안내';d.querySelector('p').textContent='독자 월 이용권 없이 무료 작품·무료 회차를 읽습니다. 기본 글쓰기·연재·공개는 무료입니다. 소장 작가 85%·후원 작가 90%는 배분 예시입니다. 후원은 준비 중입니다.';}}
 const nav=document.querySelector('.music-bottom-nav');
 const studioMenu=document.querySelector('#studio .studio>.side');
 if(studioMenu){studioMenu.classList.add('studio-section-nav');studioMenu.setAttribute('role','navigation');studioMenu.setAttribute('aria-label','작가 스튜디오 메뉴');studioMenu.hidden=true;document.querySelector('main').prepend(studioMenu);
 studioMenu.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(saveBeforeMobileNavigation()===false)return;if(b.dataset.go==='register')openNewBookRegistration();else go(b.dataset.go);});}
 function syncStudioMenu(id){if(!studioMenu)return;studioMenu.hidden=!['studio','books','register','editor','publishing','publish','paper','global','revenue'].includes(id);
 const current=id==='editor'?'register':['publish','paper','global'].includes(id)?'publishing':id;
 studioMenu.querySelectorAll('[data-go]').forEach(b=>{const active=b.dataset.go===current;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}

 function descriptions(){for(const card of document.querySelectorAll('#bookGrid .book-card,#discoverGrid .book-card')){if(card.querySelector('.mobile-book-description,.web-book-description'))continue;const intro=card.querySelector('.book-copy.intro'),note=card.querySelector('.book-copy.note');if(!intro&&!note)continue;const d=document.createElement('div');d.className='mobile-book-description';d.tabIndex=0;d.setAttribute('role','region');d.setAttribute('aria-label','책 소개와 작가의 말');if(intro)d.append(intro);if(note)d.append(note);card.insertBefore(d,card.querySelector('.book-foot'));}}
 descriptions();for(const id of ['bookGrid','discoverGrid'])new MutationObserver(descriptions).observe(document.getElementById(id),{childList:true});
 function fitHome(){const home=document.getElementById('home');if(!home.classList.contains('active'))return;const grid=document.getElementById('bookGrid'),navHeight=nav?.getBoundingClientRect().height||74;const available=Math.max(90,innerHeight-navHeight-grid.getBoundingClientRect().top-20);grid.style.setProperty('height',Math.min(innerWidth<=760?300:450,available)+'px','important');grid.style.setProperty('max-height',available+'px','important');grid.style.setProperty('min-height','0px','important');home.style.setProperty('max-height',Math.max(100,innerHeight-navHeight-document.querySelector('.top').getBoundingClientRect().bottom)+'px','important');home.style.setProperty('overflow-y','auto','important');}
 function catalog(){const rows=PYEODA_SERVER.connected?PYEODA_SERVER.publicBooks:[...shelves.popular.items,...shelves.new.items,...shelves.owned.items];return [...new Map(rows.map(b=>[bookKey(b),b])).values()];}
 function renderLibrary(){const grid=document.getElementById('musicLibraryGrid'),progress=readingStore();grid.replaceChildren();const rows=catalog().filter(b=>progress[bookKey(b)]&&progress[bookKey(b)].state!=='first');if(!rows.length){const p=document.createElement('p');p.className='discover-empty';p.textContent='읽기 시작한 작품이 이곳에 모입니다.';grid.append(p);}for(const b of rows){const button=document.createElement('button');button.className='music-menu';button.textContent=b.title+' · '+readHint(progress[bookKey(b)])+' ›';button.onclick=()=>openReader(b,progress[bookKey(b)]);grid.append(button);}}
 function sync(){const id=document.querySelector('.screen.active')?.id||'home';syncStudioMenu(id);nav?.querySelectorAll('button').forEach(b=>{const target=b.dataset.go,on=id===target||(target==='my'&&['studio','books','publishing','publish','paper','global','revenue'].includes(id))||(target==='register'&&id==='editor');b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(id==='library')renderLibrary();if(id==='my'){const u=PYEODA_SERVER.authUser;document.getElementById('musicProfileName').textContent=readerIsSignedIn()?(u.user_metadata?.full_name||u.user_metadata?.name||'펴다 독자'):'나의 펴다';document.getElementById('musicProfileStatus').textContent=readerIsSignedIn()?'':'무료 작품은 로그인 없이 읽을 수 있어요.';}}
 function fitWriter(){const editor=document.getElementById('editor');if(!editor.classList.contains('active'))return;const view=window.visualViewport;const start=Math.max(document.querySelector('.top').getBoundingClientRect().bottom,studioMenu&&!studioMenu.hidden?studioMenu.getBoundingClientRect().bottom:0,view?.offsetTop||0);const bottom=(view?.offsetTop||0)+(view?.height||innerHeight);editor.style.setProperty('--music-writing-height',Math.max(100,bottom-start-(nav?.getBoundingClientRect().height||74))+'px');}
 let navigationFrame=0;function scheduleSync(){cancelAnimationFrame(navigationFrame);navigationFrame=requestAnimationFrame(()=>{navigationFrame=0;sync();fitWriter();fitHome();});}
 for(const s of document.querySelectorAll('.screen'))new MutationObserver(scheduleSync).observe(s,{attributes:true,attributeFilter:['class']});
 window.addEventListener('resize',()=>{fitWriter();fitHome();});window.visualViewport?.addEventListener('resize',fitWriter);new ResizeObserver(()=>{fitWriter();fitHome();}).observe(document.querySelector('.top'));for(const node of document.querySelectorAll('#home .hero,#home .mobile-quick-memo,#home .shelf-head'))new ResizeObserver(fitHome).observe(node);requestAnimationFrame(fitHome);
 nav?.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(saveBeforeMobileNavigation()===false)return;if(b.dataset.go==='register')openNewBookRegistration();else go(b.dataset.go);});
 document.querySelectorAll('[data-music-go]').forEach(b=>b.onclick=()=>go(b.dataset.musicGo));document.querySelectorAll('[data-music-login]').forEach(b=>b.onclick=()=>document.getElementById('authorAuthBtn').click());
 const search=document.getElementById('musicBookSearch');function filterSearch(){const q=search.value.trim().toLocaleLowerCase();let count=0;for(const c of document.querySelectorAll('#discoverGrid .book-card')){const on=!q||c.textContent.toLocaleLowerCase().includes(q);c.style.setProperty('display',on?'grid':'none','important');if(on)count++;}document.getElementById('musicSearchStatus').textContent=q?`${count}권을 찾았어요.`:'';}search.addEventListener('input',filterSearch);new MutationObserver(filterSearch).observe(document.getElementById('discoverGrid'),{childList:true});
 sync();
})();
/* Private account photo: keep only one compressed thumbnail per user. */
(()=>{
 'use strict';
 const profile=document.querySelector('#my .music-profile'),image=profile?.querySelector('img');if(!image)return;
 const fallback=image.getAttribute('src'),bucket='books-profile-photos';
 const photo=document.createElement('button');photo.type='button';photo.className='music-avatar-button';photo.setAttribute('aria-label','프로필 사진 변경');image.before(photo);photo.append(image);const badge=document.createElement('span');badge.textContent='+';badge.setAttribute('aria-hidden','true');photo.append(badge);

 const dialog=document.createElement('dialog');dialog.className='music-plan-dialog music-photo-dialog';dialog.setAttribute('aria-labelledby','musicPhotoTitle');dialog.innerHTML='<header><h2 id="musicPhotoTitle">프로필 사진</h2><button type="button" data-photo-close aria-label="닫기">×</button></header><img class="music-photo-preview" alt="프로필 사진 미리보기"><label class="music-photo-select">사진 선택<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/heic,image/heif" data-photo-file></label><p class="note">사진의 가운데를 정사각형으로 맞춰 저장합니다.</p><p data-photo-status role="status" aria-live="polite"></p><div class="music-choice-actions"><button type="button" class="primary" data-photo-save disabled>저장</button><button type="button" data-photo-remove>기본 아이콘으로</button></div>';document.body.append(dialog);
 const preview=dialog.querySelector('img'),input=dialog.querySelector('input'),status=dialog.querySelector('[data-photo-status]'),save=dialog.querySelector('[data-photo-save]'),remove=dialog.querySelector('[data-photo-remove]'),close=dialog.querySelector('[data-photo-close]');
 let owner=null,displayURL=null,previewURL=null,pending=null,busy=false,loadSequence=0,selectSequence=0,authClient=null;
 const account=()=>{const u=PYEODA_SERVER.authUser;return u&&!u.is_anonymous?u.id:null;};
 function clearPreview(){++selectSequence;pending=null;input.value='';save.disabled=true;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;}
 function resetImage(){if(displayURL)URL.revokeObjectURL(displayURL);displayURL=null;image.src=fallback;image.alt='PYODA BOOKS';}
 function showBlob(blob){resetImage();displayURL=URL.createObjectURL(blob);image.src=displayURL;image.alt='내 프로필 사진';}
 async function load(force=false){const id=account();if(!force&&id===owner)return;owner=id;const seq=++loadSequence;resetImage();if(!id||!PYEODA_SERVER.client)return;try{const {data,error}=await PYEODA_SERVER.client.storage.from(bucket).download(id+'/avatar.jpg');if(seq!==loadSequence||account()!==id)return;if(!error&&data?.type==='image/jpeg')showBlob(data);}catch(e){/* Keep the default when offline. */}}
 function open(){if(!account()){document.getElementById('authorAuthBtn').click();return;}clearPreview();status.textContent='';preview.src=image.src;remove.disabled=busy;dialog.showModal();load(true).then(()=>{if(dialog.open&&!pending)preview.src=image.src;});}
 photo.onclick=open;close.onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',clearPreview);
 input.onchange=async()=>{const file=input.files?.[0];if(!file)return;clearPreview();const seq=selectSequence;status.textContent='사진 준비 중…';let url=null;try{if(!/^image\/(jpeg|png|webp|gif|heic|heif)$/.test(file.type))throw new Error('JPG·PNG·WEBP 사진을 선택해 주세요.');if(file.size>20*1024*1024)throw new Error('20MB 이하 사진을 선택해 주세요.');url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(seq!==selectSequence||!dialog.open)return;if(img.naturalWidth*img.naturalHeight>50000000)throw new Error('사진 크기가 너무 큽니다. 크기를 줄인 뒤 다시 선택해 주세요.');const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');ctx.fillStyle='#f5f0e7';ctx.fillRect(0,0,256,256);const size=Math.min(img.naturalWidth,img.naturalHeight);ctx.drawImage(img,(img.naturalWidth-size)/2,(img.naturalHeight-size)/2,size,size,0,0,256,256);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',0.82));if(seq!==selectSequence||!dialog.open)return;if(!blob||blob.size>102400)throw new Error('사진을 줄이지 못했어요. 다른 사진을 선택해 주세요.');pending=blob;previewURL=URL.createObjectURL(blob);preview.src=previewURL;save.disabled=false;status.textContent='미리보기를 확인하고 저장해 주세요.';}catch(e){if(seq===selectSequence)status.textContent=e.message.includes('사진')?e.message:'이 사진을 열지 못했어요. JPG·PNG로 변환한 뒤 선택해 주세요.';}finally{if(url)URL.revokeObjectURL(url);}};
 async function change(deleting){const id=account();if(!id||busy||(!deleting&&!pending))return;busy=true;const blob=pending;save.disabled=remove.disabled=input.disabled=close.disabled=true;status.textContent=deleting?'기본 아이콘으로 변경 중…':'사진 저장 중…';try{const storage=PYEODA_SERVER.client.storage.from(bucket);const result=deleting?await storage.remove([id+'/avatar.jpg']):await storage.upload(id+'/avatar.jpg',blob,{contentType:'image/jpeg',upsert:true,cacheControl:'0'});if(result.error)throw result.error;if(account()!==id)return;++loadSequence;owner=id;if(deleting)resetImage();else showBlob(blob);preview.src=image.src;clearPreview();status.textContent=deleting?'기본 아이콘으로 변경했어요.':'프로필 사진을 저장했어요.';}catch(e){status.textContent='저장하지 못했어요. 연결을 확인한 뒤 다시 눌러 주세요.';}finally{busy=false;remove.disabled=input.disabled=close.disabled=false;save.disabled=!pending;}}
 save.onclick=()=>change(false);remove.onclick=()=>change(true);
 function bindAuth(){const client=PYEODA_SERVER.client;if(!client||client===authClient)return;authClient=client;client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||owner&&session?.user?.id!==owner){++loadSequence;owner=null;resetImage();dialog.close();}setTimeout(()=>load(true),30);});load(true);}
 new MutationObserver(()=>{bindAuth();if(document.getElementById('my').classList.contains('active'))load(true);}).observe(document.getElementById('my'),{attributes:true,attributeFilter:['class']});
 new MutationObserver(()=>{bindAuth();load();}).observe(document.getElementById('authorAuthBtn'),{childList:true,subtree:true,characterData:true});bindAuth();window.addEventListener('online',()=>load(true));
})();

/* Home masthead matches PYODA MUSIC and shares the existing account photo. */
(()=>{
 'use strict';
 const top=document.querySelector('.top'),auth=document.getElementById('authorAuthBtn');
 if(!top||!auth)return;
 const actions=document.createElement('div');actions.className='books-header-actions';
 const avatar=document.createElement('button');avatar.type='button';avatar.className='books-header-avatar';avatar.setAttribute('aria-label','내 프로필 보기');
 const image=document.createElement('img');image.alt='내 프로필';image.src='./icon-192.png?v=books1';avatar.append(image);
 const session=document.createElement('button');session.type='button';session.className='books-header-pill';session.textContent='로그인';
 actions.append(avatar,session);top.append(actions);
 avatar.onclick=()=>{if(readerIsSignedIn())go('my');else auth.click();};
 session.onclick=async()=>{if(!readerIsSignedIn()){auth.click();return;}session.disabled=true;try{await logoutAuthor();}finally{session.disabled=false;syncHeader();}};
 const source=document.querySelector('#my .music-avatar-button img')||document.querySelector('#my .music-profile img');
 function syncHeader(){const signed=readerIsSignedIn();session.textContent=signed?'로그아웃':'로그인';avatar.setAttribute('aria-label',signed?'내 프로필 보기':'로그인');image.src=source?.getAttribute('src')||'./icon-192.png?v=books1';}
 if(source)new MutationObserver(syncHeader).observe(source,{attributes:true,attributeFilter:['src','alt']});
 new MutationObserver(syncHeader).observe(auth,{childList:true,subtree:true,characterData:true});
 let bound=null;function bind(){const client=PYEODA_SERVER.client;if(client&&client!==bound){bound=client;client.auth.onAuthStateChange(()=>setTimeout(syncHeader,0));}syncHeader();}
 new MutationObserver(bind).observe(auth,{childList:true,subtree:true,characterData:true});bind();
})();

/* Refresh installed app assets. */
(()=>{
 if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration().then(reg=>reg?.update()).catch(()=>{});
})();
