/* Reuses the existing app feature handlers and server client. */
(()=>{
 'use strict';document.body.classList.add('pyeoda-music');document.querySelector('meta[name="theme-color"]')?.setAttribute('content','#0d0d12');const css=document.querySelector('link[data-pyeoda-music]');if(css)document.head.append(css);
 const logo=document.querySelector('.top .logo');if(logo){logo.innerHTML='PYODA <small>BOOKS</small>';logo.setAttribute('aria-label','PYODA BOOKS 홈');}
 const install=document.getElementById('pyeodaInstallEntry');if(install){install.textContent='↓ 앱 설치';install.setAttribute('aria-label','PC·모바일에 펴다 앱 설치');}
 const hero=document.querySelector('#home .hero');if(hero){hero.querySelector('.eyebrow').textContent='YOUR NEXT STORY';hero.querySelector('h1').innerHTML='마음에 남을 이야기,<br>여기서 펼쳐보세요.';const copy=hero.querySelector('.hero-copy')||hero.querySelector('p');copy.textContent='새로운 작품을 만나고, 나만의 이야기를 써보세요.';const d=hero.querySelector('.mobile-home-details');if(d){d.querySelector('summary').textContent='글쓰기·다국어 출판 안내';d.querySelector('p').textContent='원고를 쓰고 연재하며 한국어·영어·일본어·중국어로 출판할 수 있습니다. 판매 수수료는 30%이며 작가 배분은 세금 등 추가 공제 전 70%입니다.';}}
 const nav=document.querySelector('.music-bottom-nav');let refreshSequence=0;
 function descriptions(){for(const card of document.querySelectorAll('#bookGrid .book-card,#discoverGrid .book-card')){if(card.querySelector('.mobile-book-description,.web-book-description'))continue;const intro=card.querySelector('.book-copy.intro'),note=card.querySelector('.book-copy.note');if(!intro&&!note)continue;const d=document.createElement('div');d.className='mobile-book-description';d.tabIndex=0;d.setAttribute('role','region');d.setAttribute('aria-label','책 소개와 작가의 말');if(intro)d.append(intro);if(note)d.append(note);card.insertBefore(d,card.querySelector('.book-foot'));}}
 descriptions();for(const id of ['bookGrid','discoverGrid'])new MutationObserver(descriptions).observe(document.getElementById(id),{childList:true});
 function fitHome(){const home=document.getElementById('home');if(!home.classList.contains('active'))return;const grid=document.getElementById('bookGrid'),navHeight=nav?.getBoundingClientRect().height||74;const available=Math.max(90,innerHeight-navHeight-grid.getBoundingClientRect().top-20);grid.style.setProperty('height',Math.min(innerWidth<=760?300:450,available)+'px','important');grid.style.setProperty('max-height',available+'px','important');grid.style.setProperty('min-height','0px','important');home.style.setProperty('max-height',Math.max(100,innerHeight-navHeight-document.querySelector('.top').getBoundingClientRect().bottom)+'px','important');home.style.setProperty('overflow-y','auto','important');}
 async function refreshPass(){const seq=++refreshSequence,labels=[...document.querySelectorAll('[data-books-pass-status]')];if(!readerIsSignedIn()){labels.forEach(x=>x.textContent='로그인 후 이용권을 확인하세요.');return;}labels.forEach(x=>x.textContent='이용권 확인 중…');try{const {data,error}=await PYEODA_SERVER.client.rpc('books_test_pass_status');if(error)throw error;if(seq!==refreshSequence)return;labels.forEach(x=>x.textContent=data.active?'테스트 이용권 · '+new Date(data.valid_until).toLocaleDateString('ko-KR')+'까지':'활성 이용권 없음');}catch(e){if(seq===refreshSequence)labels.forEach(x=>x.textContent='확인하지 못했어요. 다시 확인해 주세요.');console.warn(e);}}
 function catalog(){const rows=PYEODA_SERVER.connected?PYEODA_SERVER.publicBooks:[...shelves.popular.items,...shelves.new.items,...shelves.owned.items];return [...new Map(rows.map(b=>[bookKey(b),b])).values()];}
 function renderLibrary(){const grid=document.getElementById('musicLibraryGrid'),progress=readingStore();grid.replaceChildren();const rows=catalog().filter(b=>progress[bookKey(b)]&&progress[bookKey(b)].state!=='first');if(!rows.length){const p=document.createElement('p');p.className='discover-empty';p.textContent='읽기 시작한 작품이 이곳에 모입니다.';grid.append(p);}for(const b of rows){const button=document.createElement('button');button.className='music-menu';button.textContent=b.title+' · '+readHint(progress[bookKey(b)])+' ›';button.onclick=()=>openReader(b,progress[bookKey(b)]);grid.append(button);}}
 function sync(){const id=document.querySelector('.screen.active')?.id||'home';nav?.querySelectorAll('button').forEach(b=>{const target=b.dataset.go,on=id===target||(target==='my'&&['studio','books','publishing','publish','paper','global','revenue','plans'].includes(id))||(target==='register'&&id==='editor');b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(id==='library')renderLibrary();if(id==='my'){const u=PYEODA_SERVER.authUser;document.getElementById('musicProfileName').textContent=readerIsSignedIn()?(u.user_metadata?.full_name||u.user_metadata?.name||'펴다 독자'):'나의 펴다';document.getElementById('musicProfileStatus').textContent=readerIsSignedIn()?'웹·모바일에서 같은 계정으로 이용하세요.':'무료 작품은 로그인 없이 읽을 수 있어요.';}if(['my','plans'].includes(id))refreshPass();}
 function fitWriter(){const editor=document.getElementById('editor');if(!editor.classList.contains('active'))return;const view=window.visualViewport;const start=Math.max(document.querySelector('.top').getBoundingClientRect().bottom,view?.offsetTop||0);const bottom=(view?.offsetTop||0)+(view?.height||innerHeight);editor.style.setProperty('--music-writing-height',Math.max(100,bottom-start-(nav?.getBoundingClientRect().height||74))+'px');}
 let navigationFrame=0;function scheduleSync(){cancelAnimationFrame(navigationFrame);navigationFrame=requestAnimationFrame(()=>{navigationFrame=0;sync();fitWriter();fitHome();});}
 for(const s of document.querySelectorAll('.screen'))new MutationObserver(scheduleSync).observe(s,{attributes:true,attributeFilter:['class']});
 window.addEventListener('resize',()=>{fitWriter();fitHome();});window.visualViewport?.addEventListener('resize',fitWriter);new ResizeObserver(()=>{fitWriter();fitHome();}).observe(document.querySelector('.top'));for(const node of document.querySelectorAll('#home .hero,#home .mobile-quick-memo,#home .shelf-head'))new ResizeObserver(fitHome).observe(node);requestAnimationFrame(fitHome);
 nav?.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(saveBeforeMobileNavigation()===false)return;if(b.dataset.go==='register')openNewBookRegistration();else go(b.dataset.go);});
 document.querySelectorAll('[data-music-go]').forEach(b=>b.onclick=()=>go(b.dataset.musicGo));document.querySelectorAll('[data-music-login]').forEach(b=>b.onclick=()=>document.getElementById('authorAuthBtn').click());
 const search=document.getElementById('musicBookSearch');function filterSearch(){const q=search.value.trim().toLocaleLowerCase();let count=0;for(const c of document.querySelectorAll('#discoverGrid .book-card')){const on=!q||c.textContent.toLocaleLowerCase().includes(q);c.style.setProperty('display',on?'grid':'none','important');if(on)count++;}document.getElementById('musicSearchStatus').textContent=q?`${count}권을 찾았어요.`:'';}search.addEventListener('input',filterSearch);new MutationObserver(filterSearch).observe(document.getElementById('discoverGrid'),{childList:true});
 const login=()=>{if(readerIsSignedIn())return true;document.getElementById('authorAuthBtn').click();return false;};document.getElementById('musicPassRefresh').onclick=refreshPass;
 const dialog=document.createElement('dialog');dialog.className='music-plan-dialog';dialog.setAttribute('aria-labelledby','musicPassCheckoutTitle');dialog.innerHTML='<header><h2 id="musicPassCheckoutTitle">월 이용권 모의 결제</h2><button type="button" data-close aria-label="닫기">×</button></header><span class="music-test-badge">실제 청구 0원 · 자동 갱신 없음</span><h3>독자 월 이용권</h3><p>테스트 금액 <b>8,690원</b> · 성공 시 30일 테스트 이용권을 서버에 저장합니다.</p><p class="note">이용권 도입 전 결제 흐름 확인용입니다. 유료 회차 구매와 소장 PDF는 기존 결제를 이용합니다.</p><p data-result role="status" aria-live="polite"></p><div class="music-choice-actions"><button type="button" class="primary" data-outcome="paid">모의 결제 성공</button><button type="button" data-outcome="failed">실패 테스트</button><button type="button" data-outcome="cancelled">취소 테스트</button></div>';document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();let order=null,busy=false;const result=dialog.querySelector('[data-result]'),buttons=[...dialog.querySelectorAll('[data-outcome]')];
 document.getElementById('musicBuyPass').onclick=async()=>{if(!login()||busy)return;busy=true;order=null;result.textContent='주문 준비 중…';buttons.forEach(b=>b.disabled=true);dialog.showModal();try{const {data,error}=await PYEODA_SERVER.client.rpc('create_books_test_pass_order',{p_request_id:crypto.randomUUID()});if(error)throw error;order=data;result.textContent='테스트할 결과를 선택하세요.';buttons.forEach(b=>b.disabled=false);}catch(e){result.textContent='주문을 준비하지 못했어요. 연결을 확인하고 다시 시도해 주세요.';console.error(e);}finally{busy=false;}};
 buttons.forEach(b=>b.onclick=async()=>{if(!order||busy)return;busy=true;buttons.forEach(x=>x.disabled=true);try{const {data,error}=await PYEODA_SERVER.client.rpc('finish_books_test_pass_order',{p_order_id:order.id,p_outcome:b.dataset.outcome});if(error)throw error;result.textContent=data.status==='paid'?'모의 결제 완료 · 30일 테스트 이용권을 저장했습니다.':data.status==='failed'?'실패 결과를 저장했습니다. 실제 청구는 없습니다.':'취소 결과를 저장했습니다. 실제 청구는 없습니다.';order=null;await refreshPass();}catch(e){result.textContent='결과를 확인하지 못했어요. 같은 주문으로 다시 시도해 주세요.';buttons.forEach(x=>x.disabled=false);console.error(e);}finally{busy=false;}});
 document.getElementById('musicPassHistory').onclick=async()=>{if(!login())return;const out=document.getElementById('musicPassOrders');out.textContent='내역 확인 중…';try{const {data,error}=await PYEODA_SERVER.client.from('books_test_pass_orders').select('status,amount_krw,created_at').order('created_at',{ascending:false}).limit(30);if(error)throw error;out.replaceChildren();for(const r of data){const p=document.createElement('p');p.className='music-menu';p.textContent=new Date(r.created_at).toLocaleDateString('ko-KR')+' · '+({paid:'모의 결제 완료',failed:'실패',cancelled:'취소',pending:'대기'}[r.status]||r.status)+' · '+r.amount_krw.toLocaleString()+'원';out.append(p);}if(!data.length)out.textContent='이용권 모의 결제 내역이 없습니다.';}catch(e){out.textContent='내역을 불러오지 못했어요. 다시 시도해 주세요.';console.error(e);}};sync();
})();
/* Private account photo: keep only one compressed thumbnail per user. */
(()=>{
 'use strict';
 const profile=document.querySelector('#my .music-profile'),image=profile?.querySelector('img');if(!image)return;
 const fallback=image.getAttribute('src'),bucket='books-profile-photos';
 const photo=document.createElement('button');photo.type='button';photo.className='music-avatar-button';photo.setAttribute('aria-label','프로필 사진 변경');image.before(photo);photo.append(image);const badge=document.createElement('span');badge.textContent='+';badge.setAttribute('aria-hidden','true');photo.append(badge);
 const edit=document.createElement('button');edit.type='button';edit.className='music-photo-edit';edit.textContent='사진 변경';profile.querySelector('div').append(edit);
 const dialog=document.createElement('dialog');dialog.className='music-plan-dialog music-photo-dialog';dialog.setAttribute('aria-labelledby','musicPhotoTitle');dialog.innerHTML='<header><h2 id="musicPhotoTitle">프로필 사진</h2><button type="button" data-photo-close aria-label="닫기">×</button></header><img class="music-photo-preview" alt="프로필 사진 미리보기"><label class="music-photo-select">사진 선택<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/heic,image/heif" data-photo-file></label><p class="note">사진의 가운데를 정사각형으로 맞춰 저장합니다.</p><p data-photo-status role="status" aria-live="polite"></p><div class="music-choice-actions"><button type="button" class="primary" data-photo-save disabled>저장</button><button type="button" data-photo-remove>기본 아이콘으로</button></div>';document.body.append(dialog);
 const preview=dialog.querySelector('img'),input=dialog.querySelector('input'),status=dialog.querySelector('[data-photo-status]'),save=dialog.querySelector('[data-photo-save]'),remove=dialog.querySelector('[data-photo-remove]'),close=dialog.querySelector('[data-photo-close]');
 let owner=null,displayURL=null,previewURL=null,pending=null,busy=false,loadSequence=0,selectSequence=0,authClient=null;
 const account=()=>{const u=PYEODA_SERVER.authUser;return u&&!u.is_anonymous?u.id:null;};
 function clearPreview(){++selectSequence;pending=null;input.value='';save.disabled=true;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;}
 function resetImage(){if(displayURL)URL.revokeObjectURL(displayURL);displayURL=null;image.src=fallback;image.alt='PYODA BOOKS';}
 function showBlob(blob){resetImage();displayURL=URL.createObjectURL(blob);image.src=displayURL;image.alt='내 프로필 사진';}
 async function load(force=false){const id=account();if(!force&&id===owner)return;owner=id;const seq=++loadSequence;resetImage();if(!id||!PYEODA_SERVER.client)return;try{const {data,error}=await PYEODA_SERVER.client.storage.from(bucket).download(id+'/avatar.jpg');if(seq!==loadSequence||account()!==id)return;if(!error&&data?.type==='image/jpeg')showBlob(data);}catch(e){/* Keep the default when offline. */}}
 function open(){if(!account()){document.getElementById('authorAuthBtn').click();return;}clearPreview();status.textContent='';preview.src=image.src;remove.disabled=busy;dialog.showModal();load(true).then(()=>{if(dialog.open&&!pending)preview.src=image.src;});}
 photo.onclick=open;edit.onclick=open;close.onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',clearPreview);
 input.onchange=async()=>{const file=input.files?.[0];if(!file)return;clearPreview();const seq=selectSequence;status.textContent='사진 준비 중…';let url=null;try{if(!/^image\/(jpeg|png|webp|gif|heic|heif)$/.test(file.type))throw new Error('JPG·PNG·WEBP 사진을 선택해 주세요.');if(file.size>20*1024*1024)throw new Error('20MB 이하 사진을 선택해 주세요.');url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(seq!==selectSequence||!dialog.open)return;if(img.naturalWidth*img.naturalHeight>50000000)throw new Error('사진 크기가 너무 큽니다. 크기를 줄인 뒤 다시 선택해 주세요.');const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');ctx.fillStyle='#f5f0e7';ctx.fillRect(0,0,256,256);const size=Math.min(img.naturalWidth,img.naturalHeight);ctx.drawImage(img,(img.naturalWidth-size)/2,(img.naturalHeight-size)/2,size,size,0,0,256,256);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',0.82));if(seq!==selectSequence||!dialog.open)return;if(!blob||blob.size>102400)throw new Error('사진을 줄이지 못했어요. 다른 사진을 선택해 주세요.');pending=blob;previewURL=URL.createObjectURL(blob);preview.src=previewURL;save.disabled=false;status.textContent='미리보기를 확인하고 저장해 주세요.';}catch(e){if(seq===selectSequence)status.textContent=e.message.includes('사진')?e.message:'이 사진을 열지 못했어요. JPG·PNG로 변환한 뒤 선택해 주세요.';}finally{if(url)URL.revokeObjectURL(url);}};
 async function change(deleting){const id=account();if(!id||busy||(!deleting&&!pending))return;busy=true;const blob=pending;save.disabled=remove.disabled=input.disabled=close.disabled=true;status.textContent=deleting?'기본 아이콘으로 변경 중…':'사진 저장 중…';try{const storage=PYEODA_SERVER.client.storage.from(bucket);const result=deleting?await storage.remove([id+'/avatar.jpg']):await storage.upload(id+'/avatar.jpg',blob,{contentType:'image/jpeg',upsert:true,cacheControl:'0'});if(result.error)throw result.error;if(account()!==id)return;++loadSequence;owner=id;if(deleting)resetImage();else showBlob(blob);preview.src=image.src;clearPreview();status.textContent=deleting?'기본 아이콘으로 변경했어요.':'프로필 사진을 저장했어요.';}catch(e){status.textContent='저장하지 못했어요. 연결을 확인한 뒤 다시 눌러 주세요.';}finally{busy=false;remove.disabled=input.disabled=close.disabled=false;save.disabled=!pending;}}
 save.onclick=()=>change(false);remove.onclick=()=>change(true);
 function bindAuth(){const client=PYEODA_SERVER.client;if(!client||client===authClient)return;authClient=client;client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||owner&&session?.user?.id!==owner){++loadSequence;owner=null;resetImage();dialog.close();}setTimeout(()=>load(true),30);});load(true);}
 new MutationObserver(()=>{bindAuth();if(document.getElementById('my').classList.contains('active'))load(true);}).observe(document.getElementById('my'),{attributes:true,attributeFilter:['class']});
 new MutationObserver(()=>{bindAuth();load();}).observe(document.getElementById('authorAuthBtn'),{childList:true,subtree:true,characterData:true});bindAuth();window.addEventListener('online',()=>load(true));
})();
