/* Reuses the existing app feature handlers and server client. */
(()=>{
 'use strict';document.body.classList.add('pyeoda-music');const css=document.querySelector('link[data-pyeoda-music]');if(css)document.head.append(css);
 const logo=document.querySelector('.top .logo');if(logo){logo.innerHTML='PYODA <small>BOOKS</small>';logo.setAttribute('aria-label','PYODA BOOKS 홈');}
 const install=document.getElementById('pyeodaInstallEntry');if(install){install.textContent='↓ 앱 설치';install.setAttribute('aria-label','PC·모바일에 펴다 앱 설치');}
 const hero=document.querySelector('#home .hero');if(hero){hero.querySelector('.eyebrow').textContent='YOUR NEXT STORY';hero.querySelector('h1').innerHTML='마음에 남을 이야기,<br>여기서 펼쳐보세요.';const copy=hero.querySelector('.hero-copy')||hero.querySelector('p');copy.textContent='새로운 작품을 만나고, 나만의 이야기를 써보세요.';const d=hero.querySelector('.mobile-home-details');if(d){d.querySelector('summary').textContent='글쓰기·다국어 출판 안내';d.querySelector('p').textContent='원고를 쓰고 연재하며 한국어·영어·일본어·중국어로 출판할 수 있습니다. 판매 수수료는 30%이며 작가 배분은 세금 등 추가 공제 전 70%입니다.';}}
 const nav=document.querySelector('.music-bottom-nav');let refreshSequence=0;
 function descriptions(){for(const card of document.querySelectorAll('#bookGrid .book-card,#discoverGrid .book-card')){if(card.querySelector('.mobile-book-description,.web-book-description'))continue;const intro=card.querySelector('.book-copy.intro'),note=card.querySelector('.book-copy.note');if(!intro&&!note)continue;const d=document.createElement('div');d.className='mobile-book-description';d.tabIndex=0;d.setAttribute('role','region');d.setAttribute('aria-label','책 소개와 작가의 말');if(intro)d.append(intro);if(note)d.append(note);card.insertBefore(d,card.querySelector('.book-foot'));}}
 descriptions();for(const id of ['bookGrid','discoverGrid'])new MutationObserver(descriptions).observe(document.getElementById(id),{childList:true});
 function fitHome(){const home=document.getElementById('home');if(!home.classList.contains('active'))return;const grid=document.getElementById('bookGrid'),navHeight=nav?.getBoundingClientRect().height||74;const available=Math.max(90,innerHeight-navHeight-grid.getBoundingClientRect().top-20);grid.style.setProperty('height',Math.min(innerWidth<=760?300:450,available)+'px','important');grid.style.setProperty('max-height',available+'px','important');grid.style.setProperty('min-height','0px','important');home.style.setProperty('max-height',Math.max(100,innerHeight-navHeight-document.querySelector('.top').getBoundingClientRect().bottom)+'px','important');home.style.setProperty('overflow-y','auto','important');}
 async function refreshPass(){const seq=++refreshSequence,labels=[...document.querySelectorAll('[data-books-pass-status]')];if(!readerIsSignedIn()){labels.forEach(x=>x.textContent='로그인 후 이용권을 확인하세요.');return;}labels.forEach(x=>x.textContent='이용권 확인 중…');try{const {data,error}=await PYEODA_SERVER.client.rpc('books_test_pass_status');if(error)throw error;if(seq!==refreshSequence)return;labels.forEach(x=>x.textContent=data.active?'테스트 이용권 · '+new Date(data.valid_until).toLocaleDateString('ko-KR')+'까지':'활성 이용권 없음');}catch(e){if(seq===refreshSequence)labels.forEach(x=>x.textContent='확인하지 못했어요. 다시 확인해 주세요.');console.warn(e);}}
 function catalog(){const rows=PYEODA_SERVER.connected?PYEODA_SERVER.publicBooks:[...shelves.popular.items,...shelves.new.items,...shelves.owned.items];return [...new Map(rows.map(b=>[bookKey(b),b])).values()];}
 function renderLibrary(){const grid=document.getElementById('musicLibraryGrid'),progress=readingStore();grid.replaceChildren();const rows=catalog().filter(b=>progress[bookKey(b)]&&progress[bookKey(b)].state!=='first');if(!rows.length){const p=document.createElement('p');p.className='discover-empty';p.textContent='읽기 시작한 작품이 이곳에 모입니다.';grid.append(p);}for(const b of rows){const button=document.createElement('button');button.className='music-menu';button.textContent=b.title+' · '+readHint(progress[bookKey(b)])+' ›';button.onclick=()=>openReader(b,progress[bookKey(b)]);grid.append(button);}}
 function sync(){const id=document.querySelector('.screen.active')?.id||'home';nav?.querySelectorAll('button').forEach(b=>{const target=b.dataset.go,on=id===target||(target==='my'&&['studio','books','publishing','publish','paper','global','revenue','plans'].includes(id))||(target==='register'&&id==='editor');b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(id==='library')renderLibrary();if(id==='my'){const u=PYEODA_SERVER.authUser;document.getElementById('musicProfileName').textContent=readerIsSignedIn()?(u.user_metadata?.full_name||u.user_metadata?.name||'펴다 독자'):'나의 펴다';document.getElementById('musicProfileStatus').textContent=readerIsSignedIn()?'웹·모바일에서 같은 계정으로 이용하세요.':'무료 작품은 로그인 없이 읽을 수 있어요.';}if(['my','plans'].includes(id))refreshPass();}
 function fitWriter(){const editor=document.getElementById('editor');if(!editor.classList.contains('active'))return;const view=window.visualViewport;const start=Math.max(document.querySelector('.top').getBoundingClientRect().bottom,view?.offsetTop||0);const bottom=(view?.offsetTop||0)+(view?.height||innerHeight);editor.style.setProperty('--music-writing-height',Math.max(100,bottom-start-(nav?.getBoundingClientRect().height||74))+'px');}
 let navigationFrame=0;function scheduleSync(){cancelAnimationFrame(navigationFrame);navigationFrame=requestAnimationFrame(()=>{navigationFrame=0;sync();fitWriter();fitHome();});}
 for(const s of document.querySelectorAll('.screen'))new MutationObserver(scheduleSync).observe(s,{attributes:true,attributeFilter:['class']});
 window.addEventListener('resize',()=>{fitWriter();fitHome();});window.visualViewport?.addEventListener('resize',fitWriter);new ResizeObserver(()=>{fitWriter();fitHome();}).observe(document.querySelector('.top'));for(const node of document.querySelectorAll('#home .hero,#home .mobile-quick-memo,#home .shelf-head'))new ResizeObserver(fitHome).observe(node);requestAnimationFrame(fitHome);
 nav?.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(saveBeforeMobileNavigation()===false)return;if(b.dataset.go==='register')openNewBookRegistration();else go(b.dataset.go);});
 document.querySelectorAll('[data-music-go]').forEach(b=>b.onclick=()=>go(b.dataset.musicGo));document.querySelectorAll('[data-music-login]').forEach(b=>b.onclick=()=>document.getElementById('authorAuthBtn').click());
 const search=document.getElementById('musicBookSearch');function filterSearch(){const q=search.value.trim().toLocaleLowerCase();let count=0;for(const c of document.querySelectorAll('#discoverGrid .book-card')){const on=!q||c.textContent.toLocaleLowerCase().includes(q);c.style.setProperty('display',on?'grid':'none','important');if(on)count++;}document.getElementById('musicSearchStatus').textContent=q?`${count}권을 찾았어요.`:'';}search.addEventListener('input',filterSearch);new MutationObserver(filterSearch).observe(document.getElementById('discoverGrid'),{childList:true});
 const login=()=>{if(readerIsSignedIn())return true;document.getElementById('authorAuthBtn').click();return false;};document.getElementById('musicPassRefresh').onclick=refreshPass;
 const dialog=document.createElement('dialog');dialog.className='music-plan-dialog';dialog.setAttribute('aria-labelledby','musicPassCheckoutTitle');dialog.innerHTML='<header><h2 id="musicPassCheckoutTitle">월 이용권 모의 결제</h2><button type="button" data-close aria-label="닫기">×</button></header><span class="music-test-badge">실제 청구 0원 · 자동 갱신 없음</span><h3>독자 월 이용권</h3><p>테스트 금액 <b>8,690원</b> · 성공 시 30일 테스트 이용권을 서버에 저장합니다.</p><p class="note">이용권 도입 전 결제 흐름 확인용입니다. 유료 회차 구매와 소장 PDF는 기존 결제를 이용합니다.</p><p data-result role="status" aria-live="polite"></p><div class="music-choice-actions"><button type="button" class="primary" data-outcome="paid">모의 결제 성공</button><button type="button" data-outcome="failed">실패 테스트</button><button type="button" data-outcome="cancelled">취소 테스트</button></div>';document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();let order=null,busy=false;const result=dialog.querySelector('[data-result]'),buttons=[...dialog.querySelectorAll('[data-outcome]')];
 document.getElementById('musicBuyPass').onclick=async()=>{if(!login()||busy)return;busy=true;order=null;result.textContent='주문 준비 중…';buttons.forEach(b=>b.disabled=true);dialog.showModal();try{const {data,error}=await PYEODA_SERVER.client.rpc('create_books_test_pass_order',{p_request_id:crypto.randomUUID()});if(error)throw error;order=data;result.textContent='테스트할 결과를 선택하세요.';buttons.forEach(b=>b.disabled=false);}catch(e){result.textContent='주문을 준비하지 못했어요. 연결을 확인하고 다시 시도해 주세요.';console.error(e);}finally{busy=false;}};
 buttons.forEach(b=>b.onclick=async()=>{if(!order||busy)return;busy=true;buttons.forEach(x=>x.disabled=true);try{const {data,error}=await PYEODA_SERVER.client.rpc('finish_books_test_pass_order',{p_order_id:order.id,p_outcome:b.dataset.outcome});if(error)throw error;result.textContent=data.status==='paid'?'모의 결제 완료 · 30일 테스트 이용권을 저장했습니다.':data.status==='failed'?'실패 결과를 저장했습니다. 실제 청구는 없습니다.':'취소 결과를 저장했습니다. 실제 청구는 없습니다.';order=null;await refreshPass();}catch(e){result.textContent='결과를 확인하지 못했어요. 같은 주문으로 다시 시도해 주세요.';buttons.forEach(x=>x.disabled=false);console.error(e);}finally{busy=false;}});
 document.getElementById('musicPassHistory').onclick=async()=>{if(!login())return;const out=document.getElementById('musicPassOrders');out.textContent='내역 확인 중…';try{const {data,error}=await PYEODA_SERVER.client.from('books_test_pass_orders').select('status,amount_krw,created_at').order('created_at',{ascending:false}).limit(30);if(error)throw error;out.replaceChildren();for(const r of data){const p=document.createElement('p');p.className='music-menu';p.textContent=new Date(r.created_at).toLocaleDateString('ko-KR')+' · '+({paid:'모의 결제 완료',failed:'실패',cancelled:'취소',pending:'대기'}[r.status]||r.status)+' · '+r.amount_krw.toLocaleString()+'원';out.append(p);}if(!data.length)out.textContent='이용권 모의 결제 내역이 없습니다.';}catch(e){out.textContent='내역을 불러오지 못했어요. 다시 시도해 주세요.';console.error(e);}};sync();
})();
