import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
import * as access from '../supabase/functions/book-downloads/access.ts';
const book={id:'b1681ea4-7b32-4e76-a640-a4c5d288d1d6',owner_id:'owner',published:true,completed:true,price:4900,age_rating:'all',title:'책'},user={id:'buyer'};
const order={buyer_id:user.id,book_id:book.id,product_key:'book:'+book.id,status:'confirmed',environment:'test'};
const pdf=new TextEncoder().encode('%PDF-1.7\n%%EOF');
test('whole-book approval unlocks all formats at the same book price',()=>{assert(access.canDownload({book,user,orders:[order]}));assert.equal(book.price,4900)});
test('pending, failed, live, episode-only, other-user and other-book orders never grant test file access',()=>{for(const change of [{status:'pending'},{status:'failed'},{environment:'live'},{product_key:'episode:'+book.id+':6'},{buyer_id:'other'},{book_id:'other'}])assert.equal(access.canDownload({book,user,orders:[{...order,...change}]}),false)});
test('guest and anonymous accounts cannot download, while verified owner can preview draft files',()=>{assert.equal(access.canDownload({book,orders:[order]}),false);assert.equal(access.canDownload({book,user:{...user,is_anonymous:true},orders:[order]}),false);assert(access.canDownload({book:{...book,published:false},user:{id:'owner'},orders:[]}))});
test('adult purchases require both current verification and approved review',()=>{const adult={...book,age_rating:'19',adult_review_status:'approved'};assert.equal(access.canDownload({book:adult,user,orders:[order]}),false);assert(access.canDownload({book:adult,user,orders:[order],adultVerified:true}));assert.equal(access.canDownload({book:{...adult,adult_review_status:'pending'},user,orders:[order],adultVerified:true}),false)});
test('signature check rejects HTML and arbitrary ZIP renamed PDF or EPUB',()=>{assert.equal(access.publicationMime(pdf,'pdf'),'application/pdf');assert.equal(access.publicationMime(new TextEncoder().encode('<script>bad</script>'),'pdf'),null);assert.equal(access.publicationMime(new Uint8Array([80,75,3,4]),'epub'),null);const epub=new Uint8Array(58);epub.set([80,75,3,4]);epub[26]=8;epub.set(new TextEncoder().encode('mimetypeapplication/epub+zip'),30);assert.equal(access.publicationMime(epub,'epub'),'application/epub+zip')});
let source=readFileSync('supabase/functions/book-downloads/index.ts','utf8').replace(/^import .*;\n/gm,'').replace('Deno.serve(handle);','');source=stripTypeScriptTypes(source);
const factory=new Function('createClient','AwsClient','Deno',...Object.keys(access),source.replace('export async function handle','async function handle')+'\nreturn handle;');
const id='e1681ea4-7b32-4e76-a640-a4c5d288d1d6';
function setup({account=user,orders=[order],storedBook=book,headOK=true}={}){
 const operations=[];let upserted=null,hash='',size=0;
 const file={id,book_id:book.id,language:'ko',format:'pdf',filename:'책_ko.pdf',object_key:'downloads/private',byte_size:pdf.length};
 const records={books:[storedBook],payment_orders:orders,book_download_files:[file],adult_verifications:[]};
 function from(table){const filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},upsert(row){upserted=row;return q},then(resolve){resolve({data:(records[table]||[]).filter(row=>filters.every(([k,v])=>row[k]===v)),error:null})},async maybeSingle(){return {data:(records[table]||[]).find(row=>filters.every(([k,v])=>row[k]===v))||null,error:null}}};return q;}
 const admin={auth:{async getUser(){return{data:{user:account}}}},from};
 class R2{async fetch(url,options={}){operations.push(options.method||'GET');if(options.method==='PUT'){size=options.body.length;hash=options.headers['x-amz-meta-sha256'];return new Response('')}if(options.method==='HEAD')return new Response(null,{status:headOK?200:503,headers:{'content-length':String(size),'x-amz-meta-sha256':hash}});return new Response(pdf)}}
 const env={SUPABASE_URL:'https://local',SUPABASE_SERVICE_ROLE_KEY:'server-only',PYEODA_R2_ACCOUNT_ID:'a'.repeat(32),PYEODA_R2_ACCESS_KEY_ID:'key',PYEODA_R2_SECRET_ACCESS_KEY:'secret',PYEODA_R2_PRIVATE_BUCKET:'private-files',PYEODA_R2_UPLOADS_ENABLED:'true'};
 const handle=factory(()=>admin,R2,{env:{get:k=>env[k]}},...Object.values(access));return {handle,operations,get upserted(){return upserted}};
}
function request(action,options={}){return new Request('https://local?action='+action+'&bookId='+book.id+'&id='+id+'&language=ko&format=pdf',{headers:{authorization:'Bearer test'},...options})}
test('unpaid buyer and guest are denied before any R2 read',async()=>{for(const options of [{orders:[]},{account:null}]){const f=setup(options);assert.ok([401,403].includes((await f.handle(request('read'))).status));assert.deepEqual(f.operations,[])}});
test('catalog reveals file choices but no object keys or reusable download URLs',async()=>{const f=setup({account:null});const response=await f.handle(request('list'));const data=await response.json();assert.equal(response.status,200);assert.equal(data.canDownload,false);assert.equal(data.price,4900);assert(!JSON.stringify(data).includes('object_key'));assert(!JSON.stringify(data).includes('downloads/private'));assert.deepEqual(f.operations,[])});
test('authenticated paid download proxies bytes with private caching and correct attachment type',async()=>{const f=setup();const response=await f.handle(request('read'));assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'application/pdf');assert.equal(response.headers.get('cache-control'),'private, no-store');assert(response.headers.get('content-disposition').startsWith('attachment;'));assert.deepEqual(new Uint8Array(await response.arrayBuffer()),pdf)});
test('file ID from another book cannot be downloaded using an owned book entitlement',async()=>{const f=setup();const req=new Request('https://local?action=read&bookId='+book.id+'&id=aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',{headers:{authorization:'Bearer test'}});assert.equal((await f.handle(req)).status,404);assert.deepEqual(f.operations,[])});
test('nonowner upload fails before bytes are stored',async()=>{const f=setup();assert.equal((await f.handle(request('upload',{method:'POST',body:pdf}))).status,403);assert.equal(f.upserted,null);assert.deepEqual(f.operations,[])});
test('owner upload verifies the R2 object before recording the downloadable file',async()=>{const f=setup({account:{id:'owner'}});assert.equal((await f.handle(request('upload',{method:'POST',body:pdf}))).status,200);assert.deepEqual(f.operations,['PUT','HEAD']);assert.equal(f.upserted.book_id,book.id);assert.equal(f.upserted.byte_size,pdf.length)});
test('failed storage verification preserves the previous registered file',async()=>{const f=setup({account:{id:'owner'},headOK:false});assert.equal((await f.handle(request('upload',{method:'POST',body:pdf}))).status,503);assert.equal(f.upserted,null)});
